### ISSUE TITLE
Gulp inline changing case of custom attributes in HTML markup

### ISSUE THREAD

**Issue by onebitrocket** [ashaffer/gulp-inline#40] opened 2016-06-27 07:18 UTC
I  have a Gulp task to inline CSS and JS into my HTML file:

```
gulp.task('html', function () {
    gulp.src(source + '**/*.+(html|php)')
    .pipe($.plumber())
    .pipe($.inline({
        base: source,
        disabledTypes: ['svg', 'img']
    }))
    .pipe(gulp.dest(build))
    .pipe(reload({
        stream: true
    }));
});
```

I'm finding that the inline plugin is making changes to my HTML markup. Most noticeably it is changing the case of attributes.

`mktoName="Banner Heading"` becomes `mktoname="Banner Heading"`

Is there a fix for this?

I tried adding html to the disabledType options, but this did nothing?
I cannot change the casing of the name of this attribute, it related to marketo templates

Thanks

**Comment by maxkoryukov** [comment] 2016-12-22 07:20
Caused by cheeriojs/cheerio#74

fixed in #48

**Closed** 2016-12-22 19:58 UTC
